### ISSUE TITLE
如果 title 中含有 / 会保存失败

### ISSUE THREAD

**Issue by jerrylususu** [jerrylususu/bookmark-summary#2]
可能需要一个更健壮的slugger
https://github.com/jerrylususu/bookmark-collection/actions/runs/10705197205/job/29679992461
```
Traceback (most recent call last):
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 218, in <module>
    main()
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 215, in main
    process_bookmark_file()
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 30, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 193, in process_bookmark_file
    with open(get_text_content_path(title), 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'bookmark-summary/20[24](https://github.com/jerrylususu/bookmark-collection/actions/runs/10705197205/job/29679992461#step:6:25)09/2024-09-04-zeyi-lin/hivisionidphotos:-⚡️hivisionidphotos:-a-lightweight-and-efficient-ai-id-photos-tools.-一个轻量级的ai证件照制作算法。_raw.md'
```

**Comment by jerrylususu** [comment]
这似乎是同一个问题
https://github.com/jerrylususu/bookmark-collection/actions/runs/10739334882/job/29784843814

```
Traceback (most recent call last):
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 218, in <module>
    main()
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 215, in main
    process_bookmark_file()
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 30, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/bookmark-collection/bookmark-collection/bookmark-summary/process_changes.py", line 193, in process_bookmark_file
    with open(get_text_content_path(title), 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'bookmark-summary/20[24](https://github.com/jerrylususu/bookmark-collection/actions/runs/10705197205/job/29679992461#step:6:25)09/2024-09-06-no-more-“expert,-intermediate,-beginner”:-classifying-talks-in-call-for-papers/conference-agendas-|-christian-heilmann_raw.md'
```

**Comment by jerrylususu** [comment]
哦，我明白了，本质上是因为 存在 '/' 所以认为多了一级目录...

**Comment by jerrylususu** [comment]
和 #3 是一个问题了

**Comment by jerrylususu** [comment]
在 1b2e560 和 45d3adb 中已修复
